### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RhinoCodes** [semc-labs/NexusAuroraTaskBoard#2]
- [x] Basic Task Functionality
- [x] Make it so only council can create tasks
- [x] Add leaderboard 
- [ ] Add alternate method of making tasks (Slash Commands)
- [ ] Add configuration of who can accept tasks (in custom dashboard?)
- [ ] Make it so it works straight out of the box for other servers
